# Generated by Django 3.2.24 on 2024-03-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
