# Generated by Django 3.2.24 on 2024-04-16 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Adminapp', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Wears', 'Wears'), ('Lotions', 'Lotions'), ('Gym kits', 'Gym Kits')], max_length=30)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
