# Generated by Django 3.2.24 on 2024-04-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0011_auto_20240416_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='user_id',
        ),
    ]
